resources:
  - url: http://127.0.0.1:5000/aftership-card.js
    type: module
views:
  - cards:
      - type: custom:aftership-card
        title: Aftership Card Development
        entity: sensor.aftership
